// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreCraftApi.Data;

#nullable disable

namespace ScoreCraftApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240203105805_MatchTB")]
    partial class MatchTB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoreCraftApi.Enities.Match", b =>
                {
                    b.Property<int>("RefMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefMatch"));

                    b.Property<int>("BestOf")
                        .HasColumnType("int");

                    b.Property<string>("Formate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RefGuestTeam")
                        .HasColumnType("int");

                    b.Property<int?>("RefHomeTeam")
                        .HasColumnType("int");

                    b.Property<int?>("RefMatchWinner")
                        .HasColumnType("int");

                    b.Property<int?>("TeamRefTeam")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserRefUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefMatch");

                    b.HasIndex("RefGuestTeam");

                    b.HasIndex("RefHomeTeam");

                    b.HasIndex("RefMatchWinner");

                    b.HasIndex("TeamRefTeam");

                    b.HasIndex("UserRefUser");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.MatchResult", b =>
                {
                    b.Property<int>("RefMatchResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefMatchResult"));

                    b.Property<int?>("GuestResult")
                        .HasColumnType("int");

                    b.Property<int?>("HomeResult")
                        .HasColumnType("int");

                    b.Property<int?>("RefMatch")
                        .HasColumnType("int");

                    b.HasKey("RefMatchResult");

                    b.HasIndex("RefMatch");

                    b.ToTable("MatchResult");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.Team", b =>
                {
                    b.Property<int?>("RefTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RefTeam"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefTeam");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.User", b =>
                {
                    b.Property<Guid>("RefUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefTeam")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isTeamCaptain")
                        .HasColumnType("bit");

                    b.HasKey("RefUser");

                    b.HasIndex("RefTeam");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.Match", b =>
                {
                    b.HasOne("ScoreCraftApi.Enities.Team", "GuestTeam")
                        .WithMany()
                        .HasForeignKey("RefGuestTeam")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreCraftApi.Enities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("RefHomeTeam")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreCraftApi.Enities.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("RefMatchWinner")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreCraftApi.Enities.Team", null)
                        .WithMany("Matches")
                        .HasForeignKey("TeamRefTeam");

                    b.HasOne("ScoreCraftApi.Enities.User", null)
                        .WithMany("Matches")
                        .HasForeignKey("UserRefUser");

                    b.Navigation("GuestTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.MatchResult", b =>
                {
                    b.HasOne("ScoreCraftApi.Enities.Match", "Match")
                        .WithMany("MatchResults")
                        .HasForeignKey("RefMatch");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.User", b =>
                {
                    b.HasOne("ScoreCraftApi.Enities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("RefTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.Match", b =>
                {
                    b.Navigation("MatchResults");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.Team", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.User", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
