// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreCraftApi.Data;

#nullable disable

namespace ScoreCraftApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240203100738_TeamsTb")]
    partial class TeamsTb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoreCraftApi.Enities.Team", b =>
                {
                    b.Property<int?>("RefTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RefTeam"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefTeam");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.User", b =>
                {
                    b.Property<Guid>("RefUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefTeam")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefUser");

                    b.HasIndex("RefTeam");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoreCraftApi.Enities.User", b =>
                {
                    b.HasOne("ScoreCraftApi.Enities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("RefTeam");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
